apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
