apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminer.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "adminer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
